# Generated by Django 5.1.1 on 2024-09-08 20:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, verbose_name='nome')),
                ('number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. O formato deve ser (xx) xxxx-xxxx ou (xx) xxxxx-xxxx.', regex='^\\(\\d{2}\\) \\d{4}-\\d{4}$|^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='número')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chips', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'chip',
                'verbose_name_plural': 'chips',
            },
        ),
    ]
