# Generated by Django 5.1.1 on 2024-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip_heater', '0002_alter_chip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='directory_token',
            field=models.CharField(default='SADFSAD', max_length=50, verbose_name='token da pasta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chip',
            name='number',
            field=models.CharField(blank=True, max_length=15, verbose_name='número'),
        ),
    ]
