# Generated by Django 5.1.1 on 2024-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip_heater', '0004_alter_chip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='stage',
            field=models.CharField(choices=[('NT', 'Não iniciado'), ('ST', 'Em aquecimento'), ('CP', 'Concluído'), ('BN', 'Banido')], default='NT', max_length=2, verbose_name='Fase'),
        ),
    ]
