# Generated by Django 5.1.1 on 2024-10-03 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip_heater', '0006_remove_chip_directory_token_chip_browser_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='mensagem')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
            },
        ),
        migrations.AlterField(
            model_name='chip',
            name='browser_profile',
            field=models.FileField(upload_to='browser_profiles', validators=[django.core.validators.FileExtensionValidator(['zip'])], verbose_name='perfil do navegador'),
        ),
    ]
