# Generated by Django 5.1.1 on 2024-10-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip_heater', '0007_message_alter_chip_browser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='days_to_heat',
            field=models.PositiveIntegerField(default=0, verbose_name='dias para aquecer'),
        ),
        migrations.AddField(
            model_name='chip',
            name='heated_days',
            field=models.PositiveIntegerField(default=0, verbose_name='dias aquecidos'),
        ),
    ]
