# Generated by Django 5.1.1 on 2024-09-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default=1, max_length=15, verbose_name='telefone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(default=1, max_length=50, verbose_name='instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=1, max_length=100, verbose_name='sobrenome'),
            preserve_default=False,
        ),
    ]
