# Generated by Django 5.1.1 on 2024-09-06 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cellphone_user_instagram_user_name_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='instagram'),
        ),
    ]
