# Generated by Django 5.1.1 on 2024-10-14 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='instagram'),
        ),
    ]
