# Generated by Django 5.1.1 on 2024-10-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID do cliente'),
        ),
        migrations.AddField(
            model_name='user',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID da assinatura'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('no plan', 'Sem plano'), ('discovery', 'Descoberta'), ('ascension', 'Ascensão'), ('elite', 'Elite'), ('vanguard', 'Vanguard'), ('prodigy', 'Prodígio'), ('supreme', 'Supremo'), ('legendary', 'Lendário'), ('infinity', 'Infinity')], default='no plan', max_length=20, verbose_name='plano de assinatura'),
        ),
    ]
